export const characters = [
    "Akuma",
    "Amaterasu",
    "Arthur",
    "C.Viper",
    "Chris",
    "Chun Li",
    "Dante",
    "Felicia",
    "Firebrand",
    "Frank West",
    "Haggar",
    "Hsien Ko",
    "Jill",
    "Morrigan",
    "Nemesis",
    "Phoenix Wright",
    "Ryu",
    "Spencer",
    "Strider",
    "Trish",
    "Tron Bonne",
    "Vergil",
    "Viewtiful Joe",
    "Wesker",
    "Zero",
    "Captain America",
    "Deadpool",
    "Doctor Doom",
    "Doctor Strange",
    "Dormammu",
    "Ghost Rider",
    "Hawkeye",
    "Hulk",
    "Iron Fist",
    "Iron Man",
    "Magneto",
    "M.O.D.O.K.",
    "Nova",
    "Phoenix",
    "Rocket Raccoon",
    "Sentinel",
    "She Hulk",
    "Shuma - Gorath",
    "Spider - Man",
    "Storm",
    "Super - Skrull",
    "Taskmaster",
    "Thor",
    "Wolverine",
    "X - 23"
]